#!/usr/bin/env python3
"""Generate an OpenCode-ready prompt for LifeOS operator goals.

Usage:
  python3 lifeos_goal_prompt.py --goal "description" --risk-tier tier2
  python3 lifeos_goal_prompt.py --goal "test mcpo sandbox" --risk-tier tier3 --output text

This script does NOT:
  - Read .env files or secrets
  - Print bearer tokens
  - Read capture content
  - Write to the canonical vault
"""

import argparse
import os
import sys

VALID_TIERS = {"tier0", "tier1", "tier2", "tier3", "tier4", "tier5"}

SAFETY_BOUNDARIES = """## Hard Boundaries

- Do not expose any service publicly.
- Do not bind anything to 0.0.0.0.
- Do not modify real .env files.
- Do not print or commit secrets or tokens.
- Do not mount canonical vault into any service or container.
- Do not touch Docker volumes except normal named volume usage.
- Do not stage runtime artifacts (.config/opencode/opencode.json, 50_Event_Log/events.jsonl, .gemini/, 30_Capture/pending_review/).
- Do not write to canonical vault except Current_Working_State.md.
- Do not create Knowledge/Project/Idea/Reference notes.
- Do not activate n8n workflows, MCP runtime, or OpenHands runtime."""

STAGING_RULES = """## Git Discipline

Do not stage:
- .config/opencode/opencode.json
- 50_Event_Log/events.jsonl
- .gemini/
- 30_Capture/pending_review/
- LifeOS_Capture_Buffer/
- LifeOS_Media_Archive/
- 40_Services/capture_api/.env
- generated Markdown capture drafts
- runtime logs
- secrets
- Docker volumes/data
- zip files

Stage only intended tracked source/config/docs/test files."""

REPORT_FORMAT = """## Final Report Format

Return exactly:
1. Interpreted Goal
2. Agent Use
3. Starting State
4. Root Cause / Implementation Summary
5. Files Changed
6. Verification Results
7. Tests
8. Safety Boundaries Preserved
9. Commit and Push
10. Manual Next Steps
11. Next Recommended Phase
12. Stop Line"""

STOP_LINE = "## Stop Line\n\nLifeOS <task-name> complete. Stop."

PHASE_PLAN = """## Phase Plan

Follow a systematic phased approach:
1. Read required files and reproduce current state.
2. Analyze root cause or design requirements.
3. Implement minimal changes using TDD where applicable.
4. Verify changes with tests and live smoke tests.
5. Run git diff --check, confirm clean state.
6. Stage only allowed files and commit.
7. Push to origin and offsite."""


def generate_prompt(goal, risk_tier):
    if risk_tier not in VALID_TIERS:
        raise ValueError(f"Invalid risk tier: {risk_tier}. Must be one of: {', '.join(sorted(VALID_TIERS))}")

    parts = []

    parts.append(f"# LifeOS Operator Task: {goal}")
    parts.append("")
    parts.append(f"**Risk Tier:** {risk_tier}")
    parts.append(f"**Generated by:** lifeos_goal_prompt.py")
    parts.append("")

    parts.append("## Interpreted Goal")
    parts.append("")
    parts.append(f"Implement the following in the LifeOS V3 repo under /home/lifeos:")
    parts.append(f"")
    parts.append(f"{goal}")
    parts.append("")

    parts.append("## Agent Deployment Policy")
    parts.append("")
    parts.append("Use agents proportionally to the task complexity.")
    parts.append("Do not deploy more agents than the task requires.")
    parts.append("If the task tool is unavailable, state that clearly and use simulated review only.")
    parts.append("")

    parts.append("## Current Environment")
    parts.append("")
    parts.append("- Root: /home/lifeos")
    parts.append("- Vault: /home/lifeos/10_Vaults/LifeOS")
    parts.append("- Capture buffer: /home/lifeos/LifeOS_Capture_Buffer")
    parts.append("- Event log: /home/lifeos/50_Event_Log/events.jsonl")
    parts.append("- All services bind 127.0.0.1 only (no public exposure)")
    parts.append("- Capture API runs on Tailscale MagicDNS for cross-device access")
    parts.append("")

    parts.append(SAFETY_BOUNDARIES)
    parts.append("")

    parts.append(STAGING_RULES)
    parts.append("")

    parts.append(REPORT_FORMAT)
    parts.append("")

    parts.append(PHASE_PLAN)
    parts.append("")

    parts.append(STOP_LINE)
    parts.append("")

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Generate an OpenCode-ready LifeOS operator prompt")
    parser.add_argument("--goal", required=True, help="Goal description")
    parser.add_argument("--risk-tier", default="tier2",
                        choices=sorted(VALID_TIERS),
                        help="Risk tier (tier0-tier5)")
    parser.add_argument("--output", default="text", choices=["text"],
                        help="Output format")
    args = parser.parse_args()

    try:
        prompt = generate_prompt(args.goal, args.risk_tier)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    print(prompt)
    return 0


if __name__ == "__main__":
    sys.exit(main())
